import type { LabConfig } from '../../types';

export const fuzzyConfig: LabConfig = {
  queryLanguage: 'query_dsl',
  queryType: 'fuzzy_query',
  displayName: 'Fuzzy Query',
  description: "Returns documents that contain terms similar to the search term, as measured by a Levenshtein edit distance. An edit distance is the number of one-character changes needed to turn one term into another. These changes can include: - Changing a character (box \u2192 fox) - Removing a character (black \u2192 lack) - Inserting a character (sic \u2192 sick) - Transposing two adjacent characters (act \u2192 cat)",
  docUrl: 'https://elastic.co/docs/reference/query-languages/query-dsl/query-dsl-fuzzy-query',

  keyDisplayFields: {
    products: 'product_name',
    product_reviews: 'review_title',
    product_users: 'username',
  },
  searchFields: {
    products: ["product_name", "product_description"],
    product_reviews: ["review_title", "review_text"],
    product_users: ["interests"],
  },
  sampleQueries: {
    products: "wireless",
    product_reviews: "comfortable",
    product_users: "Electronics",
  },
  queryStructure: {
    type: 'inline',
    fieldPath: '',
  },
  examples: [

    {
      id: '1',
      title: "Search for similar product names",
      description: "Find products with names similar to \u0027wireles\u0027 using automatic fuzziness.",
      template: `{
  "query": {
    "fuzzy": {
      "product_name": {
        "value": "wireles",
        "fuzziness": "AUTO"
      }
    }
  }
}`,
      index: 'products',

      tryThis: [

        "Try using other misspelled product names like \u0027Bluetoth\u0027 or \u0027Premum\u0027.",

      ],


      tooltips: {

        "value": "The term to search for.",

        "fuzziness": "Defines the allowed Levenshtein edit distance. \u0027AUTO\u0027 calculates based on term length.",

      },

    },

    {
      id: '2',
      title: "Find reviews with similar titles",
      description: "Search for review titles similar to \u0027comfotable\u0027 with a fuzziness of 2.",
      template: `{
  "query": {
    "fuzzy": {
      "review_title": {
        "value": "comfotable",
        "fuzziness": 2,
        "max_expansions": 20
      }
    }
  }
}`,
      index: 'product_reviews',

      tryThis: [

        "Try changing \u0027comfotable\u0027 to \u0027durabl\u0027 or \u0027qualty\u0027.",

      ],


      tooltips: {

        "value": "The term to search for.",

        "fuzziness": "Defines the maximum edit distance. Higher values allow more variations.",

        "max_expansions": "Limits the number of terms generated by the fuzzy query.",

      },

    },

    {
      id: '3',
      title: "Search user interests with prefix match",
      description: "Find user interests similar to \u0027Electornics\u0027 with a prefix length of 1.",
      template: `{
  "query": {
    "fuzzy": {
      "interests": {
        "value": "Electornics",
        "fuzziness": "AUTO",
        "prefix_length": 1
      }
    }
  }
}`,
      index: 'product_users',

      tryThis: [

        "Try using interests like \u0027Books\u0027 or \u0027SportsOutdoors\u0027 with misspellings.",

      ],


      tooltips: {

        "value": "The term to search for.",

        "fuzziness": "Defines the allowed Levenshtein edit distance.",

        "prefix_length": "Specifies the number of initial characters that must match exactly.",

      },

    },

    {
      id: '4',
      title: "Search product descriptions with transpositions enabled",
      description: "Find products with descriptions similar to \u0027wirless\u0027 using transpositions.",
      template: `{
  "query": {
    "fuzzy": {
      "product_description": {
        "value": "wirless",
        "fuzziness": "AUTO",
        "transpositions": true
      }
    }
  }
}`,
      index: 'products',

      tryThis: [

        "Try using other misspelled descriptions like \u0027premum audio\u0027 or \u0027beauty producs\u0027.",

      ],


      tooltips: {

        "value": "The term to search for.",

        "fuzziness": "Defines the allowed Levenshtein edit distance.",

        "transpositions": "Allows swapping of adjacent characters (e.g., \u0027act\u0027 \u2192 \u0027cat\u0027).",

      },

    },

    {
      id: '5',
      title: "Search user interests with constant score rewrite",
      description: "Find users with interests similar to \u0027Books\u0027 using constant score rewrite.",
      template: `{
  "query": {
    "fuzzy": {
      "interests": {
        "value": "Books",
        "fuzziness": "AUTO",
        "rewrite": "constant_score"
      }
    }
  }
}`,
      index: 'product_users',

      tryThis: [

        "Try using \u0027Electronics\u0027 or \u0027Toys\u0027 as search terms.",

      ],


      tooltips: {

        "value": "The term to search for.",

        "fuzziness": "Defines the allowed Levenshtein edit distance.",

        "rewrite": "Determines how the query scores are calculated. \u0027constant_score\u0027 applies uniform scoring.",

      },

    },

  ],
};
