import type { LabConfig } from '../../types';

export const fuzzyConfig: LabConfig = {
  queryLanguage: 'query_dsl',
  queryType: 'fuzzy_query',
  displayName: 'Fuzzy Query',
  description: "Returns documents that contain terms similar to the search term, as measured by a Levenshtein edit distance. An edit distance is the number of one-character changes needed to turn one term into another. These changes can include: - Changing a character (box \u2192 fox) - Removing a character (black \u2192 lack) - Inserting a character (sic \u2192 sick) - Transposing two adjacent characters (act \u2192 cat)",
  docUrl: 'https://elastic.co/docs/reference/query-languages/query-dsl/query-dsl-fuzzy-query',

  keyDisplayFields: {
    products: 'product_name',
    product_reviews: 'review_title',
    product_users: 'username',
  },
  searchFields: {
    products: ["product_name", "product_description"],
    product_reviews: ["review_title", "review_text"],
    product_users: ["interests"],
  },
  sampleQueries: {
    products: "wireless",
    product_reviews: "comfortable",
    product_users: "Electronics",
  },
  queryStructure: {
    type: 'inline',
    fieldPath: '',
  },
  examples: [

    {
      id: 'example_1',
      title: "Find products with similar names",
      description: "Search for products with names similar to \u0027wireles\u0027 to account for possible misspellings or typos.",
      template: `{ "query": { "fuzzy": { "product_name": { "value": "wireles", "fuzziness": "AUTO" } } } }`,
      index: 'products',

      tryThis: [

        "Change \"wireles\" to \"wirles\" and observe the results.",

        "Adjust the fuzziness parameter to 1 and rerun the query.",

      ],


      tooltips: {

        "value": "The term to search for in the fuzzy query.",

        "fuzziness": "Defines the edit distance. \u0027AUTO\u0027 adjusts based on the length of the term.",

      },

    },

    {
      id: 'example_2',
      title: "Search for reviews with similar titles",
      description: "Search for reviews with titles that closely match \u0027comfrtable\u0027.",
      template: `{ "query": { "fuzzy": { "review_title": { "value": "comfrtable", "fuzziness": "2", "prefix_length": 2 } } } }`,
      index: 'product_reviews',

      tryThis: [

        "Increase the prefix_length to 3 and check how it impacts the results.",

        "Switch fuzziness to \u0027AUTO\u0027 and compare the output.",

      ],


      tooltips: {

        "value": "The term to search for in the review_title field.",

        "fuzziness": "The maximum Levenshtein edit distance allowed.",

        "prefix_length": "The number of initial characters that must match exactly.",

      },

    },

    {
      id: 'example_3',
      title: "Locate users with similar interests",
      description: "Search for users whose interests are similar to \u0027Electonic\u0027.",
      template: `{ "query": { "fuzzy": { "interests": { "value": "Electonic", "fuzziness": "AUTO", "max_expansions": 30 } } } }`,
      index: 'product_users',

      tryThis: [

        "Reduce max_expansions to 10 and observe the narrower results.",

        "Search for \u0027Electronix\u0027 instead of \u0027Electonic\u0027.",

      ],


      tooltips: {

        "value": "The keyword to match against the interests field.",

        "max_expansions": "Limits the number of variations generated by the fuzzy query.",

      },

    },

    {
      id: 'example_4',
      title: "Find products with similar descriptions",
      description: "Search for products with descriptions close to \u0027premum wireless\u0027.",
      template: `{ "query": { "fuzzy": { "product_description": { "value": "premum wireless", "fuzziness": "1" } } } }`,
      index: 'products',

      tryThis: [

        "Change \u0027premum wireless\u0027 to \u0027premium wireles\u0027 and rerun the query.",

        "Increase fuzziness to 2 and compare the results.",

      ],


      tooltips: {

        "value": "The term to match in the product_description field.",

        "fuzziness": "Defines the allowed edit distance between the query term and the indexed terms.",

      },

    },

    {
      id: 'example_5',
      title: "Match reviews with similar text",
      description: "Search for reviews with text resembling \u0027durabl and comfortabl\u0027.",
      template: `{ "query": { "fuzzy": { "review_text": { "value": "durabl and comfortabl", "fuzziness": "AUTO" } } } }`,
      index: 'product_reviews',

      tryThis: [

        "Replace \u0027durabl and comfortabl\u0027 with \u0027durable comfort\u0027 and observe the behavior.",

        "Test with fuzziness set to 1 for stricter matching.",

      ],


      tooltips: {

        "value": "The term to match against the review_text field.",

        "fuzziness": "Allows for approximate matching by accounting for typos or close variations.",

      },

    },

  ],
};
