#!/bin/bash
# Build script for individual query lab types
# Usage: ./scripts/build-lab.sh <lab-type>
# Example: ./scripts/build-lab.sh query-string

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

LAB_TYPE=$1

if [ -z "$LAB_TYPE" ]; then
  echo "Error: Lab type required"
  echo "Usage: ./scripts/build-lab.sh <lab-type>"
  echo "Available lab types: match, query-string, bool"
  exit 1
fi

# Map lab type to config file
case $LAB_TYPE in
  match)
    CONFIG_FILE="labConfig.ts"
    ;;
  query-string)
    CONFIG_FILE="labs/queryStringConfig.ts"
    ;;
  bool)
    CONFIG_FILE="labs/boolConfig.ts"
    ;;
  *)
    echo "Error: Unknown lab type: $LAB_TYPE"
    echo "Available lab types: match, query-string, bool"
    exit 1
    ;;
esac

echo "========================================"
echo "  Building Lab: $LAB_TYPE"
echo "========================================"

# Step 1: Copy lab config
echo ""
echo "[1/3] Copying lab config..."
cd "$PROJECT_ROOT/shared/frontend/src/config"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Error: Config file not found: $CONFIG_FILE"
  exit 1
fi

# For match, it's already labConfig.ts, otherwise copy from labs/
if [ "$LAB_TYPE" != "match" ]; then
  # Extract the config name from the file
  CONFIG_NAME=$(basename "$CONFIG_FILE" .ts)
  # Import and export it as labConfig
  cat > labConfig.ts << EOF
// Auto-generated from $CONFIG_FILE
// Do not edit this file directly - edit the source file in labs/

import { ${CONFIG_NAME} } from './$CONFIG_FILE';
export const labConfig = ${CONFIG_NAME};
EOF
  echo "✓ Config copied from $CONFIG_FILE"
else
  echo "✓ Using default match config"
fi

# Step 2: Build frontend
echo ""
echo "[2/3] Building frontend..."
cd "$PROJECT_ROOT/shared/frontend"
npm run build

if [ ! -f "dist/index.html" ]; then
  echo "ERROR: Frontend build failed - dist/index.html not found"
  exit 1
fi
echo "✓ Frontend built successfully"

# Step 3: Copy to backend/static
echo ""
echo "[3/3] Copying build to backend/static..."
rm -rf "$PROJECT_ROOT/shared/backend/static/assets"
cp -r dist/* "$PROJECT_ROOT/shared/backend/static/"
echo "✓ Files copied to shared/backend/static/"

echo ""
echo "========================================"
echo "  Build complete for $LAB_TYPE lab!"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Test locally: cd shared/backend && python3 -m uvicorn main:app"
echo "2. Deploy: ./scripts/deploy-to-instruqt.sh"
echo ""

